/**
 * stateMachines.js — Canonical State Machines & Invariant Lifecycles for PrimeSchoolOS.
 * All multi-step lifecycles use strict enums defined here.
 */

export const ATTENDANCE_STATUS = {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LATE: 'LATE',
    HALF_DAY: 'HALF_DAY',
    EXCUSED: 'EXCUSED',
};

export const ATTENDANCE_CORRECTION_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
};

export const MARKS_STATUS = {
    DRAFT: 'DRAFT',
    MARKS_ENTRY: 'MARKS_ENTRY',
    SUBMITTED: 'SUBMITTED',
    VERIFIED: 'VERIFIED',
    PUBLISHED: 'PUBLISHED',
    LOCKED: 'LOCKED',
};

export const MARKS_CORRECTION_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
};

export const HOMEWORK_STATUS = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    CLOSED: 'CLOSED',
    COMPLETED: 'COMPLETED',
};

export const SUBMISSION_STATUS = {
    PENDING: 'PENDING',
    SUBMITTED: 'SUBMITTED',
    EVALUATED: 'EVALUATED',
    LATE: 'LATE',
    RESUBMIT_REQUESTED: 'RESUBMIT_REQUESTED',
};

export const PAYMENT_STATUS = {
    CREATED: 'CREATED',
    PENDING: 'PENDING',
    AUTHORIZED: 'AUTHORIZED',
    CAPTURED: 'CAPTURED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
};

export const LEAVE_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
};

export const ADMISSION_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    SHORTLISTED: 'SHORTLISTED',
    INTERVIEW: 'INTERVIEW',
    SELECTED: 'SELECTED',
    REJECTED: 'REJECTED',
    FEE_PENDING: 'FEE_PENDING',
    ENROLLED: 'ENROLLED',
    CANCELLED: 'CANCELLED',
};

export const ENROLLMENT_STATUS = {
    ENROLLED: 'ENROLLED',
    PROMOTED: 'PROMOTED',
    DETAINED: 'DETAINED',
    TRANSFERRED: 'TRANSFERRED',
    GRADUATED: 'GRADUATED',
};

export const TEACHING_ASSIGNMENT_TYPE = {
    CLASS_TEACHER: 'CLASS_TEACHER',
    SUBJECT_TEACHER: 'SUBJECT_TEACHER',
    ASSISTANT_TEACHER: 'ASSISTANT_TEACHER',
    COORDINATOR: 'COORDINATOR',
};
